### ISSUE TITLE
[FEAT] 낫투두 생성 뷰 작업

### ISSUE THREAD

**Issue by giovannijunseokim** [DO-NOTTO-DO/NotToDo-AOS#13]
## 💡 Issue
낫투두 생성 뷰 부셔버릴것이다.

## 📝 todo
- [x] 전반적 뷰 스케치
- [ ] 드롭다운 메뉴 연결
- [x] 에디트 텍스트 옆 버튼 누르면 새로운 뷰 동적 생성, 밑의 뷰 체인 다시 걸기
- [x] 바텀 시트 연결하기
- [x] 조건에 맞을 시 버튼 활성화
- [x] 메인 액티비티 - 프래그먼트 연결 함수 추가
