### ISSUE TITLE
[FEAT] 성취 뷰

### ISSUE THREAD

**Issue by giovannijunseokim** [DO-NOTTO-DO/NotToDo-AOS#16]
## 💡 Issue

캘린더 추가 전 버전 성취 뷰(프래그먼트) 만들겠습니다.

## 📝 todo

- [x] 전체 화면 스크롤
- [x] 뷰페이저2 사용
- [x] 뷰페이저2와 탭 레이아웃 연결
- [x] 중첩 리사이클러 뷰 작성
- [x] 메인 액티비티와 성취 뷰 연결
