### ISSUE TITLE
[FEAT] 검색 액티비티 추가 및 낫투두 추가 뷰 디자인 수정

### ISSUE THREAD

**Issue by giovannijunseokim** [DO-NOTTO-DO/NotToDo-AOS#25]
## 💡 Issue

- 검색 액티비티 UI 구현
- 검색 액티비티 기능 구현 및 추가 뷰와 연결
- 추가 뷰 디자인 조금씩 수정

## 📝 todo

- [x] 검색 액티비티 리사이클러 뷰 구현
- [x] 리사이클러 뷰 터치 이벤트 구현
- [x] 액티비티 전환되며 데이터 전달 기능 구현
- [x] 추가 뷰 디자인 수정
