### ISSUE TITLE
[FEAT] 통계 서버통신

### ISSUE THREAD

**Issue by giovannijunseokim** [DO-NOTTO-DO/NotToDo-AOS#38]
## 📝 todo

- [x] 낫투두 통계 Dto 제작
- [x] 상황별 통계 Dto 제작
- [x] 통계 서비스 제작
- [x] 데이터 유무에 따른 분기처리 UI에 반영
- [x] 받아온 낫투두 통계 UI 반영
- [x] 받아온 상황별 통계 UI 반영
