### ISSUE TITLE
[FEAT] 문자열 추출, 코드 다이어트

### ISSUE THREAD

**Issue by giovannijunseokim** [DO-NOTTO-DO/NotToDo-AOS#61]
## 💡 Issue

- XML 스트링 리소스 추출
- 필요없는 코드 삭제

## 📝 todo

- [x] addition XML 스트링 리소스 추출, 코드 정리
- [x] search XML 스트링 리소스 추출, 코드 정리
- [x] achievement XML 스트링 리소스 추출, 코드 정리
- [x] on_board XML 스트링 리소스 추출, 코드 정리
- [x] 캘린더 bottom sheet 스트링 리소스 추출, 코드 정리
- [x] 드롭다운 코드 삭제
- [x] Test.kt 파일 삭제
