### ISSUE TITLE
[FEAT] 추가 뷰에서 행동 추천 뷰, 상황 추가 뷰 붙이기

### ISSUE THREAD

**Issue by giovannijunseokim** [DO-NOTTO-DO/NotToDo-AOS#63]
## 💡 Issue

추가 뷰에서 행동 추천, 상황 추가 붙이고 애니메이션 추가

## 📝 todo

- [ ] 행동 추천 프래그먼트 활용해서 행동 추천 액티비티 만들기
- [ ] 추가 뷰에서 행동 추천 뷰 연결
- [ ] 추가 뷰에서 상황 추가 뷰 연결
- [ ] 액티비티 전환 애니메이션 추가
