### ISSUE TITLE
[FEAT] 상황 추가 뷰 디자인 수정 및 서버통신 연결

### ISSUE THREAD

**Issue by giovannijunseokim** [DO-NOTTO-DO/NotToDo-AOS#70]
## 💡 Issue

- 상황 추가 뷰 디자인 수정
- 상황 추가 뷰 서버통신 연결

## 📝 todo

- [x] 뷰모델 활용하여 TextWatcher 작성, 테두리 변화
- [x] DTO 작성
- [x] 서비스 작성 및 등록
- [x] 뷰모델에서 서버 통신 로직 구현
- [x] 통신 결과값 UI에 반영
- [x] 추가 뷰와 연결
