### ISSUE TITLE
[FEAT] 홈화면 작업 주간 클릭시 데이터 전송

### ISSUE THREAD

**Issue by cbj0010** [DO-NOTTO-DO/NotToDo-AOS#71]
## 💡 Issue
ui빼먹은 것들 할 것임 , 서버 못붙인거 붙일거임

## 📝 todo

- [x] 타이핑 애니메이션 적용
- [x] 새로고침 에니메이션 적용(영역 다시 잡기)
- [x] id값 전달하기
- [x] 홈화면 주간캘린더에서 클릭시 데이터 값 가져와서 get에 전달
