### ISSUE TITLE
[FEAT] 기획 QA 이후 수정사항 1

### ISSUE THREAD

**Issue by giovannijunseokim** [DO-NOTTO-DO/NotToDo-AOS#88]
## 💡 Issue

이슈
1. 낫투두 추가기록 넘어갈 때 키보드 자동 띄우기
2. 추천 뷰 바텀 마진(패딩?) 잡기
3. 상황 추가 뷰 넘어갈 때 기존 값 가져가기
4. 상황 추가 뷰에서 빈 값으로 넘어갈 시 조건 취소 및 텍스트 = 입력하기
5. 상황 추가 뷰 맨 위 텍스트 중앙
6. 9시간 전 되는 이슈 해결
7. 통계부분 순위 이미지 다시 뽑기
8. 추천 뷰 겹치는 부분 수정
9. 성취 뷰 글자수 제한
10. 스낵바 텍스트 변경

## 📝 todo

- [x] 낫투두 추가기록 넘어갈 때 키보드 자동 띄우기
- [x] 추천 뷰 바텀 마진(패딩) 잡기
- [x] 상황 추가 뷰 넘어갈 때 기존 값 가져가기
- [x] 상황 추가 뷰에서 빈 값으로 넘어갈 시 조건 취소 및 텍스트 = 입력하기
- [x] 상황 추가 뷰 맨 위 텍스트 중앙
- [x] 9시간 전 되는 이슈 해결
- [x] 통계부분 순위 이미지 다시 뽑기
- [x] 추천 뷰 겹치는 부분 수정
- [x] 성취 뷰 글자수 제한
- [x] 스낵바 텍스트 변경
