### ISSUE TITLE
[FEAT] 디자인 QA 이후 수정사항 1

### ISSUE THREAD

**Issue by giovannijunseokim** [DO-NOTTO-DO/NotToDo-AOS#90]
## 💡 Issue

1. 토스트 메시지 가운데, 랩 콘텐트(훈기형)
2. 성취 뷰 캘린더 월 볼드
3. 액션 맥스라인 1(그 외도 동일)(키보드를 내릴까 맥스라인을 잡을까)
4. 액션 플러스 버튼 오른쪽 마진 X
5. 홈 뷰 타이핑 단어가 되기 전에 미리 예상해서 줄바꿈하는것
6. 낫투두 상황별 통계 위아래 크기 늘려보고 문제있으면 이미지 다시 받기
7. 만약 추가버튼 비활성화일때 클릭시 비어있는 박스 테두리 빨간색으로 만들기
8. 행동 1,2 X버튼 옆의 텍스트랑 크기 맞추기
9. 윈도우 상태바 바로 밑 색이랑 통일시키기
10. 추천 뷰 카테고리 리스트 맨 끝에 여백주고, 최대한 맨 처음에 보이는 마지막 아이템이 오른쪽에 걸치게 만들기
11. 추천 액티비티 백 버튼 기능
12. 애니메이션 전환 속도 빠르게

## 📝 todo

- [x] 토스트 메시지 가운데, 랩 콘텐트(훈기형)
- [x] 성취 뷰 캘린더 월 볼드
- [x] 액션 맥스라인 1(그 외도 동일)(키보드를 내릴까 맥스라인을 잡을까)
- [x] 액션 플러스 버튼 오른쪽 마진 X
- [x] 홈 뷰 타이핑 단어가 되기 전에 미리 예상해서 줄바꿈하는것
- [x] 낫투두 상황별 통계 위아래 크기 늘려보고 문제있으면 이미지 다시 받기
- [x] 만약 추가버튼 비활성화일때 클릭시 비어있는 박스 테두리 빨간색으로 만들기
- [x] 행동 1,2 X버튼 옆의 텍스트랑 크기 맞추기
- [x] 윈도우 상태바 바로 밑 색이랑 통일시키기
- [x] 추천 뷰 카테고리 리스트 맨 끝에 여백주고, 최대한 맨 처음에 보이는 마지막 아이템이 오른쪽에 걸치게 만들기
- [x] 추천 액티비티 백 버튼 기능
- [x] 애니메이션 전환 속도 빠르게
- [x] 9시간 전 되는 이슈 해결
- [x] 성취 뷰 글자수 제한
- [x] 통계 뷰 낫투두명 ... 처리
